function calculateSizeMain(){let main=$('#document_Main');let tailleHeader=parseFloat((($('#document_Header').css('height')).split("px"))[0]);main.css('height',"calc(100vh - "+tailleHeader+"px - 2em)");let tailleForm="calc("+main.height()+"px - 1em)";$('#formController').css('max-height',tailleForm)}
function centerLoading(){let largeur=$('#graphZone').width()/2;let hauteur=($('#document_Main').height()/2)+32;$('#loadingDiv').css("top",hauteur+"px").css("left",largeur+"px")}
function responsiveMode(){if(window.innerWidth<=600){$('#graphController').hide();$('#closeController').on("click",function(){$('#graphController').hide()}).show();let buttonSettings=$('#showSettings');buttonSettings.on("click",function(){$('#graphController').show()}).show();$('#graphZone').css("height","calc(100% - "+buttonSettings.css("height")+")");console.log()}else{$('#graphController').show();$('#closeController, #showSettings').hide();$('#graphZone').css("height","auto")}}
$(function(){moment.locale("fr");calculateSizeMain();responsiveMode();$('#errorgraphCanvas, #errorgraphCanvasDetail').hide();$("#logout").click((e)=>{e.preventDefault();deleteCookie('token');deleteCookie('user-id');window.location=e.target.href});$('#dateDebut').datepicker({autoHide:!0,autoPick:!0,language:'fr-FR',format:'dd/mm/yyyy',weekday:1,zIndex:999999});$('#dateFin').datepicker({autoHide:!0,autoPick:!0,date:new Date((new Date()).valueOf()+1000*3600*24),language:'fr-FR',format:'dd/mm/yyyy',weekday:1,zIndex:999999}).prop('disabled',!0);$('#dateDebut, #dateFin').on("change",displayGraphDate);$('#selectBoxGraph, #selectCaptorGraph').on("change",displayGraphDate);$('input:radio[name=chooseTypeDate]').on("change",switchOptionDate);$('input:radio[name=chooseTypeDalt]').on("change",setDalton);centerLoading();callAPIForGraph("devices/"+getCookie('user-id'),fillSelectData);callAPIForGraph("sensors",fillSelectCaptor);$('#laterCache').on("click",function(){$('#dialWebApp').hide()});$(window).on("resize",function(){calculateSizeMain();responsiveMode();centerLoading()})});function callAPIForGraph(arg,func,actionGraph,idCanvasDiv,idCanvas,titleGraph,idError,label,errorLabel,labelYData,typeData,dateAPIDebut,endDate){setLoading(1);$.ajax({url:"https://api.sensorygarden.be/"+arg,type:"GET",beforeSend:function(xhr){xhr.setRequestHeader('Authorization','Bearer '+getCookie('token'))},complete:function(data){func(data,actionGraph,idCanvasDiv,idCanvas,titleGraph,idError,label,errorLabel,labelYData,typeData,dateAPIDebut,endDate);setLoading()}})}
let countCall=0;function setLoading(nombre=0){let loading=$('#loadingDiv');let connection=navigator.connection||navigator.mozConnection||navigator.webkitConnection;if(connection=connection!==undefined?connection.rtt>60:!0){if(nombre>0){loading.show();countCall+=nombre}else{countCall-=1}}
    if(countCall===0)loading.hide()}
function displayGraphDate(){let endDate;let dateAPIFin;let checkedRadio=$('input:radio[name=chooseTypeDate]:checked').attr("id");if(checkedRadio==="singleDate"){endDate=moment(new Date());dateAPIFin=endDate.format("DD-MM-YYYY")}else if(checkedRadio==="multiDate"){endDate=moment($('#dateFin').datepicker('getDate'));dateAPIFin=endDate.format("DD-MM-YYYY")}
    let selectedCaptor=$('#selectBoxGraph').val();let dateAPIDebut=moment($('#dateDebut').datepicker('getDate'));let dateAPI=dateAPIDebut.format("DD-MM-YYYY");let captor=($('#selectCaptorGraph').val()).toLowerCase();let typeData=captor.toLowerCase();let titleLabelData=titreGraphFr[typeData];let titleLabelDataAverage=titreGraphMoyenneFr[typeData];let labelYData=labelY[typeData];callAPIForGraph("records/"+selectedCaptor+"/"+captor+"/"+dateAPI,buildSimpleGraph,"upDate","divCanvasDetail","graphCanvasDetail",titleLabelData,"errorgraphCanvasDetail",titleLabelData+" le",["Heure",titleLabelData],labelYData,typeData);callAPIForGraph("records/"+selectedCaptor+"/"+captor+"/"+dateAPI+"/"+dateAPIFin,buildAverageGraphWeek,"upDate","divCanvas","graphCanvas",titleLabelDataAverage,"errorgraphCanvas",titleLabelDataAverage+" du",["Heure",titleLabelDataAverage],labelYData,typeData,dateAPIDebut,moment(endDate).add(1,"d"));callAPIForGraph("records/"+selectedCaptor+"/all/"+dateAPI,buildTableRecap,"upDate","divCanvasRecap","tableRecap","Les dernières données du "+dateAPI,"errorgraphCanvasRecap")}
function fillSelectData(response){let select="";if(response.status===401){$("#disconnectDiv").load("lostConnection.html")}
    if(response.responseJSON.status==="SUCCESS"){let boxs=response.responseJSON.data;select="";for(let item in boxs){select+="<option value="+boxs[item].device_id+">";select+=boxs[item].deviceName+"</option>"}}else{select+="<option value=''>Aucun Sensory Captor</option>"}
    $('#selectBoxGraph').html(select);initGraph()}
function initGraph(){centerLoading();let today=moment(new Date());let beforeToday=moment(today).subtract(6,"d");let captor=$('#selectBoxGraph').val();let titleLabelDataAverage=titreGraphMoyenneFr.humidite;let titleLabelData=titreGraphFr.humidite;let labelYData=labelY.humidite;let typeData="humidite";callAPIForGraph("records/"+captor+"/Humidite/"+moment(today).format("DD-MM-YYYY"),buildSimpleGraph,"draw","divCanvasDetail","graphCanvasDetail",titleLabelData,"errorgraphCanvasDetail",titleLabelData+" le",["Heure",titleLabelData],labelYData,typeData);callAPIForGraph("records/"+captor+"/all/"+moment(today).format("DD-MM-YYYY"),buildTableRecap,"draw","divCanvasRecap","tableRecap","Les dernières données du "+moment(today).format("DD-MM-YYYY"),"errorgraphCanvasRecap");callAPIForGraph("records/"+captor+"/Humidite/"+moment(beforeToday).format("DD-MM-YYYY")+"/"+moment(today).format("DD-MM-YYYY"),buildAverageGraphWeek,"draw","divCanvas","graphCanvas",titleLabelDataAverage,"errorgraphCanvas",titleLabelDataAverage+" du",["Heure",titleLabelDataAverage],labelYData,typeData,beforeToday,moment(today).add(1,"d"))}
const titreGraphFr={"humidite":"Taux d'humidité dans l'air","qualite_air":"Qualité de l'air","temperature":"Température","humidite_terre":"Taux d'humidité du sol","luminosite":"Luminosité","pression":"Pression"};const titreGraphMoyenneFr={"humidite":"Taux d'humidité moyen dans l'air","qualite_air":"Qualité de l'air moyenne","temperature":"Température moyenne","humidite_terre":"Taux d'humidité moyen du sol","luminosite":"Luminosité moyenne","pression":"Pression moyenne"};const labelY={"humidite":"Humidité de l'air (%)","qualite_air":"Qualité de l'air (AQI)","temperature":"Température (°C)","humidite_terre":"Humidité du sol (um)","luminosite":"Luminosité (Lux)","pression":"Pression (Pa)"};function fillSelectCaptor(response){let select="";let capteurFr={"Humidite":"Humidité","Qualite_air":"Qualité de l'air","Temperature":"Température","Humidite_terre":"Humidité du sol","Luminosite":"Luminosité","Pression":"Pression"};if(response.responseJSON.status==="SUCCESS"){let captors=response.responseJSON.data;for(let item in captors){select+="<option value="+captors[item].sensorName+">";select+=capteurFr[captors[item].sensorName]+"</option>"}}else{select+="<option value=''>Aucun Capteur disponible</option>"}
    $('#selectCaptorGraph').html(select)}
function switchOptionDate(sender){if(sender.target.id==="singleDate"){$("#dateFin").prop('disabled',!0);let today=moment(new Date());let beforeToday=moment(today).subtract(6,"d");let captorBox=$('#selectBoxGraph').val();let dateDebut=moment($('#dateDebut').datepicker('getDate'));let captor=($('#selectCaptorGraph').val()).toLowerCase();let typeData=captor.toLowerCase();let titleLabelData=titreGraphFr[typeData];let titleLabelDataAverage=titreGraphMoyenneFr[typeData];let labelYData=labelY[typeData];if(dateDebut>beforeToday){callAPIForGraph("records/"+captorBox+"/"+captor+"/"+moment(beforeToday).format("DD-MM-YYYY")+"/"+moment(today).format("DD-MM-YYYY"),buildAverageGraphWeek,"upDate","divCanvas","graphCanvas",titleLabelData,"errorgraphCanvas",titleLabelData+" du",["Heure",titleLabelData],labelYData,typeData,beforeToday,moment(today).add(1,"d"))}else{callAPIForGraph("records/"+captorBox+"/"+captor+"/"+moment(dateDebut).format("DD-MM-YYYY")+"/"+moment(today).format("DD-MM-YYYY"),buildAverageGraphWeek,"upDate","divCanvas","graphCanvas",titleLabelDataAverage,"errorgraphCanvas",titleLabelDataAverage+" le",["Heure",titleLabelDataAverage],labelYData,typeData,dateDebut,moment(today).add(1,"d"))}
    $("#multiDateLabel").css("backgroundColor","darkgrey")}else if(sender.target.id==="multiDate"){$("#dateFin").prop('disabled',!1);$("#multiDateLabel").css("backgroundColor","#4CAF50");displayGraphDate()}}
function setDalton(sender){daltonienEnabled=sender.target.id==="daltYes";let captor=($('#selectCaptorGraph').val()).toLowerCase();daltonMode("graphCanvas",captor,"bar");daltonMode("graphCanvasDetail",captor,"line")}
function trapFocus(element,namespace){var focusableEls=element.querySelectorAll('a[href], button, textarea, input[type="text"], input[type="email"], input[type="submit"], input[type="reset"]'),firstFocusableEl=focusableEls[0];lastFocusableEl=focusableEls[focusableEls.length-1];KEYCODE_TAB=9;firstFocusableEl.focus();element.addEventListener('keydown',function(e){var isTabPressed=(e.key==='Tab'||e.keyCode===KEYCODE_TAB);if(!isTabPressed){return}
    if(e.shiftKey){if(document.activeElement===firstFocusableEl){lastFocusableEl.focus();e.preventDefault()}}else{if(document.activeElement===lastFocusableEl){firstFocusableEl.focus();e.preventDefault()}}})}